export const CARREGAR_NOTICIAS = 'CARREGAR_NOTICIAS';
export const BUSCAR_NOTICIAS = 'BUSCAR_NOTICIAS';

export const FAVORITAR = 'FAVORITAR';
export const CARREGAR_FAVORITOS = 'CARREGAR_FAVORITOS';